### ISSUE TITLE
Bug: Warning: DOMXPath::query(): Invalid expression

### ISSUE THREAD

**Issue by ceesvanegmond** [JanDC/css-from-html-extractor#8]
Implementing the library I get an ```Symfony\Component\Debug\Exception\
ContextErrorException``` with the message ```Warning: DOMXPath::query(): Invalid expression``` on line 153.

Debugging this error, apparently the `$expression` variable on line 150 equals false.
For now I'mm using a quick fix:

```php
if (! $expression) {
    return false;
}
```

This doens't seem the right solution right? 
In the `buildExpressionForSelector` function, the `$selector` equals @fontface. 
An exceptioninterface is being thrown with the message ```Expected selector, but <delimiter "@" at 0> found.```. `false` is being returned and that's why the DOMXpath warning is thrown.

Any idea on how to fix this?

Anyhow this library is awesome 👍

**Comment by JanDC** [comment]
Hi @ceesvanegmond,

Looking at the error, it does indeed seem like the **@fontface** selector is not supported by DOMXPath.

I'll look into it, thank you for reporting this error 👍

**Comment by ceesvanegmond** [comment]
Hi @JanDC ,

Ah right. How can we fix this? I could to PR if you want.

**Comment by JanDC** [comment]
I haven't got a clue how to fix it without debugging it myself 😄 .
I'll look into it tonight, I hope it's not too critical for you to have it solved right away.

Of course you could debug it yourself and PR me if you've found something...

**Comment by ceesvanegmond** [comment]
@JanDC I've looked in to it, but i don't come any further when return false when the $expression is false.

**Comment by JanDC** [comment]
@ceesvanegmond 

I've been looking in to it, but I can't seem to generate the same error when I add a `@font-face` selector. Do you mind sending me the broken css (or a snippet)?


ping @gijsroge

**Comment by JanDC** [comment]
@ceesvanegmond , I just realized the `@fontface` selector you referenced wasn't valid and I confused it with `@font-face`.

Your suggestion is therefor valid: if an expression cannot be build, we skip the related rule since it's not a valid selector.

**Comment by ceesvanegmond** [comment]
@JanDC 👍
